import { css } from '@emotion/react';
import Head from 'next/head';
import Link from 'next/link';
import { client, usersQuery } from '../util/client';

const homeStyles = css`
  height: 90vh;
  align-items: center;
  justify-content: center;
  .big {
    font-size: 36px;
    text-align: left;
    margin: 0;
  }
  h1 {
    margin: 1vh 0 4vh 0;
    line-height: 2;
    text-align: center;
  }
  .small {
    margin: 50px 0 0 0;
  }
  .buttonStyles {
    text-decoration: none;
    color: inherit;
    margin: 5vh;
  }
`;

export default function Home() {
  return (
    <div className="pageStyles">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flexColumn" css={homeStyles}>
        <p className="big">Try new things</p>
        <p className="big">Go new places</p>
        <h1 className="h1Font"> Find your people</h1>
        <Link href="/register">
          <a className="buttonStyles">Sign up</a>
        </Link>
        <p className="small">You already have an account?</p>
        <Link href="/login">
          <a>Sign in</a>
        </Link>
      </div>
    </div>
  );
}

// this was just to try and see how that works
// export async function getServerSideProps() {
//   const { data } = await client.query({
//     query: usersQuery,
//   });

//   return {
//     props: {
//       users: data.users,
//     },
//   };
// }
